[tool.poetry]
name = "fastapi-task-manager"
version = "0.1.0"
description = "this is a task manager application"
authors = ["Pankaj"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
